apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-echo
  namespace: gorilla
spec:
  ingressClassName: nginx
  rules:
    - host: argocd-workshop-s3
      http:
        paths:
          - backend:
              service:
                name: s3-application-http-echo-svc
                port:
                  number: 80
            path: /
            pathType: Prefix
