apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
namePrefix: s3-application-

resources:
  - deployment.yaml
  - svc.yaml
  - ingress.yaml

patches:
  - target:
      kind: Deployment
      name: http-echo
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args/0
        value: -text="Hello Gorilla, this is Argo CD Workshop s3."
